In [2]:
#experiment 2(a)
import numpy as np
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
#rank
rankk=np.linalg.matrix_rank(matrix1)
print("rank=",rankk)
#determinant
determinant=np.linalg.det(matrix1)
print("determinant:",determinant)
#trace
tracee=np.trace(matrix1)
print("trace:",tracee)

rank= 2
determinant: 0.0
trace: 15


In [4]:
#expeiment 2(c)
import numpy as np
mat=np.array([[1,2],[3,4]])
v,w=np.linalg.eig(mat)
print("eigen values:",v)
print("eigen vectors:",w)

eigen values: [-0.37228132  5.37228132]
eigen vectors: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [5]:
import numpy as np
a=np.array([1,2])
b=np.array([3,4])
#printing
print("vector a:\n",a)
print("vector b:\n",b)
#inner product
print("inner product:\n",np.inner(a,b))
#outer product
print("outer product:\n",np.outer(a,b))
#cross product
print("cross product:\n",np.cross(a,b))

vector a:
 [1 2]
vector b:
 [3 4]
inner product:
 11
outer product:
 [[3 4]
 [6 8]]
cross product:
 -2


In [1]:
#experiment 3(a)
import cv2
import numpy as np
img=np.ones((350,700,3),dtype=np.uint8)*255
cv2.imshow('white image',img)
cv2.waitKey(0)

-1

In [4]:
#experiment 3(b-1)
import cv2
import numpy as np
img=cv2.imread('C:/Users/HP/Pictures/gittt.jpg')
img_array=np.array(img)
print(img_array.shape)


(162, 311, 3)


In [9]:
#experiment 3(b-2)
import numpy as np
import cv2
array1=np.zeros((100,100,3),dtype=np.uint8)
cv2.imwrite('C:/Users/HP/Pictures/gittt.jpg',array1)

True

In [25]:
#experiment 3(c)
import numpy as np
#sorting all elements
array1=np.array([1,5,2,0,3,2])
print("after sorting:",np.sort(array1))
#sorting secific elements
array2=np.array([[2,5],
                 [3,1]])
print("after sorting:",np.sort(array2,axis=-1))
#searching
array3=np.array(array1)
result=array1[array1>2]
print("searching element:",result)
#couting non zeroes
p=np.count_nonzero(array1)
print(p)
#countig specfic values
q=np.count_nonzero(array1==2)
print(q)

after sorting: [0 1 2 2 3 5]
after sorting: [[2 5]
 [1 3]]
searching element: [5 3]
5
2


In [27]:
experiment 3(d)
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
#4 rows ,3 coloumns
new_arr1=arr.reshape(4,3)
print(new_arr1)
#2x2x3 tensor
new_arr2=arr.reshape(2,2,-1)
print(new_arr2)
#1 dimension array
new_arr3=arr.reshape(-1)
print(new_arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
#bfs
graph={
    '5':['6','2'],
    '6':['3','1'],
    '2':['8'],
    '3':[],
    '1':['8'],
    '8':[]
}
visited=[]
queue=[]
def bfs(visited,graph,node):
    visited.append(node)
    queue.append(node)

    while queue:
        m=queue.pop(0)
        print(m,end=" ")

        for neighbour in graph[m]:
            if neighbour not in visited:
                visited.append(neighbour)
                queue.append(neighbour)
print("bfs:")
bfs(visited,graph,'5')

bfs:
5 6 2 3 1 8 

In [9]:
#dfs
graph={
    '5':['6','2'],
    '6':['3','1'],
    '2':['8'],
    '3':[],
    '1':['8'],
    '8':[]
}
start_node='5'
def dfs(graph,start,visited=None):
    if visited is None:
        visited=set()
    visited.add(start)
    print(start)
    for neighbour in graph[start]:
        if neighbour not in visited:
            dfs(graph,neighbour,visited)
dfs(graph,start_node)

5
6
3
1
8
2


In [16]:
from collections import defaultdict

jug1, jug2, aim = 4, 3, 2
visited = defaultdict(lambda: False)

def wjs(amt1, amt2):
    if (amt1 == 0 and amt2 == aim) or (amt1 == aim and amt2 == 0):
        print(amt1, amt2)
        return True
    if not visited[(amt1, amt2)]:
        print(amt1, amt2)
        visited[(amt1, amt2)] = True  # Corrected line
        
        return (wjs(0, amt2) or
                wjs(amt1, 0) or
                wjs(jug1, amt2) or
                wjs(amt1, jug2) or
                wjs(amt1 + min(amt2, (jug1 - amt1)),
                    amt2 - min(amt2, (jug1 - amt1))) or
                wjs(amt1 - min(amt1, (jug2 - amt2)),
                    amt2 + min(amt1, (jug2 - amt2))))
    else:
        return False

print("steps:")
wjs(0, 0)
    
        

steps:
0 0
4 0
4 3
0 3
3 0
3 3
4 2
0 2


True